spring:
  datasource:
    url: jdbc:mysql://localhost/mostova_lab1?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC
    username: root
    password: sm72mv35
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
      # Naming strategy
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8080