spring:
  datasource:
    url: jdbc:mysql://my-mysql:3306/mostova_lab1?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: create
      # Naming strategy
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8080